
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import subprocess

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Tkinter-Designer-master\build\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

text_var = ""

def update_text(value):
    global text_var
    text_var += str(value)
    canvas.itemconfig(text_display, text=text_var)

def delete_last():
    global text_var
    text_var = text_var[:-1]  # Remove the last character
    canvas.itemconfig(text_display, text=text_var)

def open_gui2(event):
    window.destroy()  # Close the current window
    subprocess.run(["python", "gui2.py"], cwd=OUTPUT_PATH)  # Run gui1.py

window = Tk()

window.geometry("800x480")
window.configure(bg = "#E5E5E5")

canvas = Canvas(
    window,
    bg = "#E5E5E5",
    height = 480,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    491.0,
    276.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    566.0,
    127.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    567.0,
    290.0,
    image=image_image_3
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: update_text(1),
    relief="flat"
)
button_1.place(
    x=58.0,
    y=92.0,
    width=80.0,
    height=70.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: update_text(2),
    relief="flat"
)
button_2.place(
    x=158.0,
    y=92.0,
    width=80.0,
    height=70.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: update_text(3),
    relief="flat"
)
button_3.place(
    x=258.0,
    y=92.0,
    width=80.0,
    height=70.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: update_text(4),
    relief="flat"
)
button_4.place(
    x=58.0,
    y=177.0,
    width=80.0,
    height=70.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: update_text(5),
    relief="flat"
)
button_5.place(
    x=158.0,
    y=177.0,
    width=80.0,
    height=70.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: update_text(6),
    relief="flat"
)
button_6.place(
    x=258.0,
    y=177.0,
    width=80.0,
    height=70.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: update_text(7),
    relief="flat"
)
button_7.place(
    x=58.0,
    y=262.0,
    width=80.0,
    height=70.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: update_text(8),
    relief="flat"
)
button_8.place(
    x=158.0,
    y=262.0,
    width=80.0,
    height=70.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: update_text(9),
    relief="flat"
)
button_9.place(
    x=258.0,
    y=262.0,
    width=80.0,
    height=70.0
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: update_text(0),
    relief="flat"
)
button_10.place(
    x=158.0,
    y=347.0,
    width=80.0,
    height=70.0
)

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=delete_last,
    relief="flat"
)
button_11.place(
    x=258.0,
    y=347.0,
    width=80.0,
    height=70.0
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    566.0,
    212.0,
    image=image_image_4
)

button_image_12 = PhotoImage(
    file=relative_to_assets("button_12.png"))
button_12 = Button(
    image=button_image_12,
    borderwidth=0,
    highlightthickness=0,
    relief="flat"
)
button_12.place(
    x=642.0,
    y=347.0,
    width=100.0,
    height=70.0
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    400.0,
    27.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    88.0,
    28.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    764.0,
    27.0,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    35.0,
    27.0,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    673.0,
    28.0,
    image=image_image_9
)

# Create a text display area
text_display = canvas.create_text(
    565.0,
    207.0,
    anchor="center",
    text=text_var,
    fill="#000000",
    font=("Inter SemiBold", 30 * -1)
)

button_12.bind("<Button-1>", open_gui2)

window.resizable(False, False)
window.mainloop()
