# System Ready

# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import subprocess

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Tkinter-Designer-master\build\assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_gui1(event):
    window.destroy()  # Close the current window
    subprocess.run(["python", "gui1.py"], cwd=OUTPUT_PATH) 

def open_gui5(event):
    window.destroy()  # Close the current window
    subprocess.run(["python", "gui5.py"], cwd=OUTPUT_PATH) 

window = Tk()

window.geometry("800x480")
window.configure(bg = "#E5E5E5")


canvas = Canvas(
    window,
    bg = "#E5E5E5",
    height = 480,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    491.0,
    276.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    400.0,
    27.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    88.0,
    28.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    764.0,
    27.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    35.0,
    27.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    673.0,
    28.0,
    image=image_image_6
)

canvas.create_text(
    296.0,
    120.0,
    anchor="nw",
    text="System Ready",
    fill="#000000",
    font=("Inter SemiBold", 30 * -1)
)

canvas.create_text(
    380.0,
    382.0,
    anchor="nw",
    text="Current Flow Rate :",
    fill="#000000",
    font=("Inter SemiBold", 20 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=58.0,
    y=347.0,
    width=100.0,
    height=70.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    relief="flat"
)
button_2.place(
    x=150.0,
    y=176.0,
    width=500.0,
    height=100.0
)

canvas.create_text(
    608.0,
    393.0,
    anchor="center",
    text="78",
    fill="#000000",
    font=("Inter SemiBold", 20 * -1)
)

canvas.create_text(
    660.0,
    382.0,
    anchor="nw",
    text="ml/min",
    fill="#000000",
    font=("Inter SemiBold", 20 * -1)
)

button_1.bind("<Button-1>", open_gui1)
button_2.bind("<Button-1>", open_gui5)

window.resizable(False, False)
window.mainloop()
