# Time

# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import subprocess
import time

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Tkinter-Designer-master\build\assets\frame6")

duration = "" 

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_gui7(event):
    window.destroy()  # Close the current window
    subprocess.run(["python", "gui7.py",duration], cwd=OUTPUT_PATH) 

def save_duration():
    global duration
    duration = canvas.itemcget(stopwatch_text, "text")
    print("Saved Duration:", duration)
    open_gui7(None)

window = Tk()

window.geometry("800x480")
window.configure(bg = "#E5E5E5")


canvas = Canvas(
    window,
    bg = "#E5E5E5",
    height = 480,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    491.0,
    276.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    400.0,
    27.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    88.0,
    28.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    764.0,
    27.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    35.0,
    27.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    673.0,
    28.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    402.0,
    183.0,
    image=image_image_7
)

canvas.create_text(
    163.0,
    165.0,
    anchor="nw",
    text="Duration",
    fill="#000000",
    font=("Inter SemiBold", 30 * -1)
)

# Stopwatch variables
start_time = time.time()
stopwatch_text = canvas.create_text(
    345.0,
    138.0,
    anchor="nw",
    text="00:00:00",
    fill="#000000",
    font=("RobotoMono Bold", 60 * -1)
)

def update_stopwatch():
    elapsed = int(time.time() - start_time)
    hours = elapsed // 3600
    minutes = (elapsed % 3600) // 60
    seconds = elapsed % 60
    time_string = f"{hours:02}:{minutes:02}:{seconds:02}"
    canvas.itemconfig(stopwatch_text, text=time_string)
    window.after(1000, update_stopwatch)  # update every 1 second

update_stopwatch()  # start updating the stopwatch

canvas.create_text(
    506.0,
    297.0,
    anchor="nw",
    text="ml/min",
    fill="#000000",
    font=("Inter SemiBold", 20 * -1)
)

canvas.create_text(
    226.0,
    297.0,
    anchor="nw",
    text="Current Flow Rate :",
    fill="#000000",
    font=("Inter SemiBold", 20 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=save_duration,
    relief="flat"
)
button_1.place(
    x=250.0,
    y=347.0,
    width=300.0,
    height=70.0
)

canvas.create_text(
    426.0,
    297.0,
    anchor="nw",
    text=" ",
    fill="#000000",
    font=("Inter SemiBold", 20 * -1)
)

# button_1.bind("<Button-1>", open_gui7)

window.resizable(False, False)
window.mainloop()
