# Take Photo

# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import subprocess
import sys

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Tkinter-Designer-master\build\assets\frame7")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_gui4(event):
    window.destroy()  # Close the current window
    subprocess.run(["python", "gui4.py"], cwd=OUTPUT_PATH) 

window = Tk()

window.geometry("800x480")
window.configure(bg = "#E5E5E5")


canvas = Canvas(
    window,
    bg = "#E5E5E5",
    height = 480,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    491.0,
    276.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    400.0,
    27.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    88.0,
    28.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    764.0,
    27.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    35.0,
    27.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    672.0,
    28.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    259.0,
    203.0,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    608.0,
    146.0,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    608.0,
    259.0,
    image=image_image_9
)

canvas.create_text(
    615.0,
    152.0,
    anchor="nw",
    text="ml/min",
    fill="#000000",
    font=("Inter SemiBold", 20 * -1)
)

canvas.create_text(
    518.0,
    118.0,
    anchor="nw",
    text="Current Flow Rate:",
    fill="#000000",
    font=("Inter SemiBold", 20 * -1)
)

canvas.create_text(
    563.0,
    228.0,
    anchor="nw",
    text="Duration:",
    fill="#000000",
    font=("Inter SemiBold", 20 * -1)
)

canvas.create_text(
    535.0,
    152.0,
    anchor="nw",
    text=" ",
    fill="#000000",
    font=("Inter SemiBold", 20 * -1)
)

# duration
duration = "00:00:00" 
if len(sys.argv) > 1:
    duration = sys.argv[1]

canvas.create_text(
    535.0,
    252.0,
    anchor="nw",
    text=duration,
    fill="#000000",
    font=("RobotoMono Bold", 30 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=83.0,
    y=336.0,
    width=248.0,
    height=70.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=483.0,
    y=336.0,
    width=250.0,
    height=70.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=355.0,
    y=336.0,
    width=80.0,
    height=70.0
)

button_2.bind("<Button-1>", open_gui4)

window.resizable(False, False)
window.mainloop()
