# Training Overview

# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import subprocess
import sys

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Tkinter-Designer-master\build\assets\frame8")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_gui(event):
    window.destroy()  # Close the current window
    subprocess.run(["python", "gui.py"], cwd=OUTPUT_PATH)  

def open_gui10(event):
    window.destroy()  # Close the current window
    subprocess.run(["python", "gui10.py"], cwd=OUTPUT_PATH) 

window = Tk()

window.geometry("800x480")
window.configure(bg = "#E5E5E5")


canvas = Canvas(
    window,
    bg = "#E5E5E5",
    height = 480,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    491.0,
    276.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    400.0,
    27.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    88.0,
    28.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    764.0,
    27.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    35.0,
    27.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    672.0,
    28.0,
    image=image_image_6
)

canvas.create_text(
    268.0,
    76.0,
    anchor="nw",
    text="Training Overview",
    fill="#000000",
    font=("Inter SemiBold", 30 * -1)
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    171.0,
    195.0,
    image=image_image_7
)

canvas.create_text(
    105.0,
    179.0,
    anchor="nw",
    text="100%",
    fill="#000000",
    font=("Inter SemiBold", 50 * -1)
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    519.0,
    181.0,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    171.0,
    306.0,
    image=image_image_9
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    519.0,
    292.0,
    image=image_image_10
)

canvas.create_text(
    339.0,
    166.0,
    anchor="nw",
    text="100%",
    fill="#000000",
    font=("Inter SemiBold", 40 * -1)
)

canvas.create_text(
    108.0,
    151.0,
    anchor="nw",
    text="Overall Score",
    fill="#000000",
    font=("Inter SemiBold", 20 * -1)
)

canvas.create_text(
    332.0,
    146.0,
    anchor="nw",
    text="Suture Accuracy",
    fill="#000000",
    font=("Inter SemiBold", 15 * -1)
)

canvas.create_text(
    339.0,
    280.0,
    anchor="nw",
    text="100%",
    fill="#000000",
    font=("Inter SemiBold", 40 * -1)
)

canvas.create_text(
    321.0,
    260.0,
    anchor="nw",
    text="Flow Rate Accuracy",
    fill="#000000",
    font=("Inter SemiBold", 15 * -1)
)

canvas.create_text(
    496.0,
    172.0,
    anchor="nw",
    text="Suture Interval",
    fill="#000000",
    font=("Inter SemiBold", 15 * -1)
)

canvas.create_text(
    619.0,
    172.0,
    anchor="nw",
    text="12234",
    fill="#000000",
    font=("Inter SemiBold", 15 * -1)
)

canvas.create_text(
    681.0,
    172.0,
    anchor="nw",
    text="mm",
    fill="#000000",
    font=("Inter SemiBold", 15 * -1)
)

canvas.create_text(
    496.0,
    269.0,
    anchor="nw",
    text="Start Value",
    fill="#000000",
    font=("Inter SemiBold", 15 * -1)
)

canvas.create_text(
    596.0,
    269.0,
    anchor="nw",
    text=" ",
    fill="#000000",
    font=("Inter SemiBold", 15 * -1)
)

canvas.create_text(
    658.0,
    269.0,
    anchor="nw",
    text="ml/min",
    fill="#000000",
    font=("Inter SemiBold", 15 * -1)
)

canvas.create_text(
    496.0,
    298.0,
    anchor="nw",
    text="End Value",
    fill="#000000",
    font=("Inter SemiBold", 15 * -1)
)

canvas.create_text(
    596.0,
    298.0,
    anchor="nw",
    text="12234",
    fill="#000000",
    font=("Inter SemiBold", 15 * -1)
)

canvas.create_text(
    658.0,
    298.0,
    anchor="nw",
    text="ml/min",
    fill="#000000",
    font=("Inter SemiBold", 15 * -1)
)

duration = "00:00:00" 
if len(sys.argv) > 1:
    duration = sys.argv[1]

canvas.create_text(
    110.0,
    284.0,
    anchor="nw",
    text=duration,
    fill="#000000",
    font=("RobotoMono Bold", 30 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=58.0,
    y=355.0,
    width=335.0,
    height=70.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    relief="flat"
)
button_2.place(
    x=407.0,
    y=355.0,
    width=335.0,
    height=70.0
)

button_1.bind("<Button-1>", open_gui)
button_2.bind("<Button-1>", open_gui10)

window.resizable(False, False)
window.mainloop()
